version: '1.0'
stages:
- checkout
- build
- push
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: 'ramunakerikanti-cloud/cf-example-build-and-push'
    revision: 'master'
    git: github
  build_my_app:
    title: Building Node.Js Docker Image
    type: build
    stage: build
    image_name: ramunakeriknati/sample-app
    working_directory: '.'
    tag: 'v1.1.0'
    dockerfile: Dockerfile
  push_to_my_registry:
    stage: 'push'
    type: push
    title: Pushing to a registry
    candidate: ${{build_my_app}}
    tag: 'v1.0.0'
    registry: ramunakerikanti
    image_name: ramunakeriknati/sample-app
    
 MyDeploy:
    title: K8s Deploy
    image: ramunakeriknati/sample-app
    commands:
      - kubectl apply -f deployment.yml   
    environment:
      - KUBECONTEXT=gke_elaborate-hash-315012_us-west1-c_quick-demo
      - KUBERNETES_NAMESPACE=default
      - MY_REPLICA_NUMBER=3 
      - PULL_SECRET=ramunakerikanti

